Document: deepin-git-dch-plugins
Title: Debian deepin-git-dch-plugins Manual
Author: <insert document author here>
Abstract: This manual describes what deepin-git-dch-plugins is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/deepin-git-dch-plugins/deepin-git-dch-plugins.sgml.gz

Format: postscript
Files: /usr/share/doc/deepin-git-dch-plugins/deepin-git-dch-plugins.ps.gz

Format: text
Files: /usr/share/doc/deepin-git-dch-plugins/deepin-git-dch-plugins.text.gz

Format: HTML
Index: /usr/share/doc/deepin-git-dch-plugins/html/index.html
Files: /usr/share/doc/deepin-git-dch-plugins/html/*.html
